apiVersion: v2
name: skyhook-explorer
description: A Kubernetes cluster visualization and management tool
type: application
version: 0.1.0
appVersion: "0.4.2"
keywords:
  - kubernetes
  - visualization
  - monitoring
  - kubectl
  - dashboard
home: https://github.com/skyhook-io/explorer
sources:
  - https://github.com/skyhook-io/explorer
maintainers:
  - name: Skyhook Team
    email: support@skyhook.io
