apiVersion: v2
name: radar
description: Modern Kubernetes visibility â€” topology, traffic, and Helm management
type: application
version: 0.6.9
appVersion: "0.6.9"
keywords:
  - kubernetes
  - visualization
  - monitoring
  - kubectl
  - dashboard
home: https://github.com/skyhook-io/radar
sources:
  - https://github.com/skyhook-io/radar
maintainers:
  - name: Skyhook Team
    email: support@skyhook.io
